
spring.application.name=api-gateway
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=auth-microservice
spring.cloud.gateway.routes[0].uri = https://back-auth-${ID_ENVIRONMENT}-ue.a.run.app/api/auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=audit-microservice
spring.cloud.gateway.routes[1].uri = https://back-audit-${ID_ENVIRONMENT}-ue.a.run.app/api/audit
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/audit/**

spring.cloud.gateway.routes[3].id=authorization-microservice
spring.cloud.gateway.routes[3].uri = https://back-authorization-${ID_ENVIRONMENT}-ue.a.run.app/api/authorization
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/authorization/**

spring.cloud.gateway.routes[4].id=client-microservice
spring.cloud.gateway.routes[4].uri = https://back-client-${ID_ENVIRONMENT}-ue.a.run.app/api/client
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/client/**

spring.cloud.gateway.routes[2].id=console-microservice
spring.cloud.gateway.routes[2].uri = https://back-console-${ID_ENVIRONMENT}-ue.a.run.app/api/console
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/console/**

spring.cloud.gateway.routes[5].id=user-microservice
spring.cloud.gateway.routes[5].uri = https://back-user-${ID_ENVIRONMENT}-ue.a.run.app/api/user
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/user/**

spring.cloud.gateway.routes[6].id=document-microservice
spring.cloud.gateway.routes[6].uri = https://back-document-${ID_ENVIRONMENT}-ue.a.run.app/api/document
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/document/**

#spring.cloud.gateway.routes[6].id=mail-microservice
#spring.cloud.gateway.routes[6].uri = https://back-mail-hfbop5vthq-ue.a.run.app/api/mail
#spring.cloud.gateway.routes[6].predicates[0]=Path=/api/mail/**

spring.cloud.gateway.routes[7].id=app-provider-microservice
spring.cloud.gateway.routes[7].uri = https://back-provider-${ID_ENVIRONMENT}-ue.a.run.app/api/provider
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/provider/**

spring.cloud.gateway.routes[8].id=app-provider-document-microservice
spring.cloud.gateway.routes[8].uri = https://back-app-provider-document-${ID_ENVIRONMENT}-ue.a.run.app/api/provider-document
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/provider-document/**

spring.cloud.gateway.routes[9].id=app-provider-general-microservice
spring.cloud.gateway.routes[9].uri = https://back-app-provider-general-${ID_ENVIRONMENT}-ue.a.run.app/api/app-provider/general
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/app-provider/general/**

spring.cloud.gateway.routes[10].id=app-provider-indicator-microservice
spring.cloud.gateway.routes[10].uri = https://back-app-provider-indicator-${ID_ENVIRONMENT}-ue.a.run.app/api/app-provider/indicator
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/app-provider/indicator/**

spring.cloud.gateway.routes[11].id=agreement-microservice
spring.cloud.gateway.routes[11].uri = https://back-agreement-${ID_ENVIRONMENT}-ue.a.run.app/api/agreement
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/agreement/**

spring.cloud.gateway.routes[12].id=chat-bot-microservice
spring.cloud.gateway.routes[12].uri = https://back-chat-${ID_ENVIRONMENT}-ue.a.run.app/api/chat
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/chat/**

spring.cloud.gateway.routes[13].id=app-payment-microservice
spring.cloud.gateway.routes[13].uri = https://back-payment-${ID_ENVIRONMENT}-ue.a.run.app/api/app-payment
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/app-payment/**

spring.cloud.gateway.routes[14].id=app-form-contract
spring.cloud.gateway.routes[14].uri = https://back-form-contract-${ID_ENVIRONMENT}-ue.a.run.app/api/form/contract
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/form/contract/**


spring.cloud.gateway.routes[15].id=app-sheets
spring.cloud.gateway.routes[15].uri = https://back-app-sheets-${ID_ENVIRONMENT}-ue.a.run.app/api/app-sheets
spring.cloud.gateway.routes[15].predicates[0]=Path=/api/app-sheets/**

spring.cloud.gateway.routes[16].id=app-health
spring.cloud.gateway.routes[16].uri = https://back-health-${ID_ENVIRONMENT}-ue.a.run.app/api/app-health
spring.cloud.gateway.routes[16].predicates[0]=Path=/api/app-health/**

server.port=8080

spring.main.web-application-type=reactive

