#Redis
spring.data.redis.host=redis-15894.c284.us-east1-2.gce.redns.redis-cloud.com
spring.data.redis.port=15894
spring.data.redis.username=default
spring.data.redis.password=o1iHHllH5OIQnfsevsUqbqeeVTQAIOwI
spring.data.redis.timeout=5000ms

server.port=8080
