
spring.application.name=api-gateway
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=auth-microservice
spring.cloud.gateway.routes[0].uri = https://back-auth-hfbop5vthq-ue.a.run.app/api/auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=audit-microservice
spring.cloud.gateway.routes[1].uri = https://back-audit-hfbop5vthq-ue.a.run.app/api/audit
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/audit/**

spring.cloud.gateway.routes[3].id=authorization-microservice
spring.cloud.gateway.routes[3].uri = https://back-authorization-hfbop5vthq-ue.a.run.app/api/authorization
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/authorization/**

spring.cloud.gateway.routes[4].id=client-microservice
spring.cloud.gateway.routes[4].uri = https://back-client-hfbop5vthq-ue.a.run.app/api/client
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/client/**

spring.cloud.gateway.routes[2].id=console-microservice
spring.cloud.gateway.routes[2].uri = https://back-console-hfbop5vthq-ue.a.run.app/api/console
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/console/**

spring.cloud.gateway.routes[5].id=user-microservice
spring.cloud.gateway.routes[5].uri = https://back-user-hfbop5vthq-ue.a.run.app/api/user
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/user/**

spring.cloud.gateway.routes[7].id=document-microservice
spring.cloud.gateway.routes[7].uri = https://back-document-hfbop5vthq-ue.a.run.app/api/document
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/document/**

spring.cloud.gateway.routes[6].id=mail-microservice
spring.cloud.gateway.routes[6].uri = https://back-mail-hfbop5vthq-ue.a.run.app/api/mail
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/mail/**

spring.cloud.gateway.routes[8].id=app-provider-microservice
spring.cloud.gateway.routes[8].uri = https://back-provider-hfbop5vthq-ue.a.run.app/api/provider
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/provider/**

spring.cloud.gateway.routes[9].id=app-provider-document-microservice
spring.cloud.gateway.routes[9].uri = https://back-app-provider-document-hfbop5vthq-ue.a.run.app/api/provider-document
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/provider-document/**

spring.cloud.gateway.routes[10].id=app-provider-general-microservice
spring.cloud.gateway.routes[10].uri = https://back-app-provider-general-hfbop5vthq-ue.a.run.app/api/app-provider/general
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/app-provider/general/**

spring.cloud.gateway.routes[11].id=app-provider-indicator-microservice
spring.cloud.gateway.routes[11].uri = https://back-app-provider-indicator-hfbop5vthq-ue.a.run.app/api/app-provider/indicator
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/app-provider/indicator/**

server.port=8080

spring.main.web-application-type=reactive
